package gestioninscription;
import java.sql.*;

public class FenNotification extends javax.swing.JFrame {    
    int numero;
    ResultSet rs;
    Connection conn;
    Statement stat;
    String pilote = "org.gjt.mm.mysql.Driver";
    public FenNotification() {        
        initComponents();        
    }
    public void init(Object maSession)
    {
        numero = (Integer)maSession;
        jLabel1.setSize(600,200);
        try
        {
            Class.forName(pilote);
            conn = DriverManager.getConnection("jdbc:mysql://localhost/formarmor","root","");
            stat = conn.createStatement();
            int i=0;
            CbxEleveAbs.addItem("---");
            rs = stat.executeQuery("select nom "
                    + "from client, plan_formation, session_formation where client.id = plan_formation.client_id "
                    + "and plan_formation.formation_id = session_formation.formation_id "
                    + "and session_formation.id = " + numero + " and effectue = 0");
            // Exploitation des resultat
            while (rs.next())
            {
                CbxEleveAbs.addItem(rs.getString(1));
                
            }
            
        }
        catch (SQLException sqlE)
        {
            System.out.println("ERREUR SQL " + sqlE.getMessage());
        }
        catch (ClassNotFoundException cnfE)
        {
            System.out.println("Erreur " + cnfE.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LblMess = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CbxEleveAbs = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Notification des Absences");
        jLabel1.setMaximumSize(new java.awt.Dimension(266, 29));
        jLabel1.setMinimumSize(new java.awt.Dimension(266, 29));
        jLabel1.setName(""); // NOI18N
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel2.setText("Nom de l'absent : ");

        CbxEleveAbs.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CbxEleveAbsItemStateChanged(evt);
            }
        });

        jButton1.setText("Envoyer");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(LblMess)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)
                        .addComponent(CbxEleveAbs, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CbxEleveAbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(LblMess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorAdded

    private void CbxEleveAbsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CbxEleveAbsItemStateChanged

        try
        {
            Class.forName(pilote);
            conn = DriverManager.getConnection("jdbc:mysql://localhost/formarmor","root","");
            stat = conn.createStatement();
            
            rs = stat.executeQuery("select nom, date_debut, libelle "
                    + "from client, plan_formation, session_formation, formation "
                    + "where client.id = plan_formation.client_id and session_formation.formation_id = formation.id "
                    + "and plan_formation.formation_id = session_formation.formation_id "
                    + "and session_formation.id = " + numero + " and effectue = 0 "
                    + "and client.nom = '" + CbxEleveAbs.getSelectedItem() + "'");
            // Exploitation des resultat
            while (rs.next())
            {
                LblMess.setText("<html> L'élève " + CbxEleveAbs.getSelectedItem() + " a été absent(e) le " + rs.getString("date_debut") + "</br>"
                        + " pour la session porté sur la formation " + rs.getString("libelle") + ".</html>");                
            }
            
        }
        catch (SQLException sqlE)
        {
            System.out.println("ERREUR SQL " + sqlE.getMessage());
        }
        catch (ClassNotFoundException cnfE)
        {
            System.out.println("Erreur " + cnfE.getMessage());
        }
        
        
        
        
    }//GEN-LAST:event_CbxEleveAbsItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked
     public static void main(String args[]) {
          FenNotification f2 = new FenNotification();
          f2.setVisible(true);   
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxEleveAbs;
    private javax.swing.JLabel LblMess;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
